services:
    node:
        image: nginx
        container_name: nginx
        volumes:
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx_def.conf:/etc/nginx/nginx.conf
            - ./volumes/log/node-nginx:/var/log/nginx
            - ../src:/var/www/html
            - sockets:/var/run/php
        ports:
            - 8080:80
        restart: unless-stopped
        depends_on:
            - php
        networks:
            - php-net
    php:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        container_name: php
        restart: unless-stopped
        volumes:
            - ./conf/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./conf/www.conf:/usr/local/etc/php-fpm.d/php.conf
            - ../src:/var/www/html
            - sockets:/var/run/php
        networks:
            - php-net
networks:
    php-net:
        name: php-network
volumes:
    sockets: